
 
const pricingData = [
    // CURSOR
    {
      toolName: "Cursor",
      planName: "Hobby",
      pricePerSeat: 0,
      flatPrice: null,
      minSensibleSeats: 1,
      maxSensibleSeats: 1,
      useCases: ["coding"],
      keyFeatures: ["limited agent requests", "limited tab completions", "evaluation only"],
      sourceUrl: "https://cursor.com/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "Cursor",
      planName: "Pro",
      pricePerSeat: 20,
      flatPrice: null,
      minSensibleSeats: 1,
      maxSensibleSeats: 19,
      useCases: ["coding"],
      keyFeatures: ["unlimited tab completions", "$20 monthly credit pool", "auto mode", "all major models"],
      sourceUrl: "https://cursor.com/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "Cursor",
      planName: "Business",
      pricePerSeat: 40,
      flatPrice: null,
      minSensibleSeats: 20,
      maxSensibleSeats: null,
      useCases: ["coding"],
      keyFeatures: ["SSO", "centralised billing", "shared team rules", "admin controls", "usage dashboard"],
      sourceUrl: "https://cursor.com/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
   
    // CHATGPT (OpenAI)

    {
      toolName: "ChatGPT",
      planName: "Plus",
      pricePerSeat: 20,
      flatPrice: null,
      minSensibleSeats: 1,
      maxSensibleSeats: 1,
      useCases: ["writing", "research", "mixed"],
      keyFeatures: ["GPT-4o access", "DALL-E image gen", "advanced data analysis", "web browsing"],
      sourceUrl: "https://openai.com/chatgpt/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "ChatGPT",
      planName: "Team",
      pricePerSeat: 25,
      flatPrice: null,
      minSensibleSeats: 2,
      maxSensibleSeats: 149,
      useCases: ["writing", "research", "mixed", "coding"],
      keyFeatures: ["higher message limits", "admin workspace", "data not used for training", "shared GPTs"],
      sourceUrl: "https://openai.com/chatgpt/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "ChatGPT",
      planName: "Enterprise",
      pricePerSeat: 60,
      flatPrice: null,
      minSensibleSeats: 150,
      maxSensibleSeats: null,
      useCases: ["writing", "research", "mixed", "coding", "data"],
      keyFeatures: ["SSO", "SCIM", "unlimited GPT-4o", "audit logs", "custom data retention", "dedicated support"],
      sourceUrl: "https://openai.com/chatgpt/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
   
    // CLAUDE (Anthropic)
    
    {
      toolName: "Claude",
      planName: "Pro",
      pricePerSeat: 20,
      flatPrice: null,
      minSensibleSeats: 1,
      maxSensibleSeats: 1,
      useCases: ["writing", "research", "coding", "mixed"],
      keyFeatures: ["Claude Sonnet access", "5x more usage than free", "projects", "priority access"],
      sourceUrl: "https://anthropic.com/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "Claude",
      planName: "Team",
      pricePerSeat: 25,
      flatPrice: null,
      minSensibleSeats: 2,
      maxSensibleSeats: 149,
      useCases: ["writing", "research", "coding", "mixed", "customer_support"],
      keyFeatures: ["higher usage limits", "centralised billing", "admin console", "data not used for training"],
      sourceUrl: "https://anthropic.com/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "Claude",
      planName: "Enterprise",
      pricePerSeat: 40,
      flatPrice: null,
      minSensibleSeats: 150,
      maxSensibleSeats: null,
      useCases: ["writing", "research", "coding", "mixed", "customer_support", "data"],
      keyFeatures: ["SSO", "SCIM", "audit logs", "200K context window", "HIPAA compliance", "custom retention"],
      sourceUrl: "https://anthropic.com/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
   
    // GITHUB COPILOT
    {
      toolName: "GitHub Copilot",
      planName: "Individual",
      pricePerSeat: 10,
      flatPrice: null,
      minSensibleSeats: 1,
      maxSensibleSeats: 1,
      useCases: ["coding"],
      keyFeatures: ["code completions", "chat in IDE", "multi-model support", "works in VS Code and JetBrains"],
      sourceUrl: "https://github.com/features/copilot#pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "GitHub Copilot",
      planName: "Business",
      pricePerSeat: 19,
      flatPrice: null,
      minSensibleSeats: 2,
      maxSensibleSeats: 99,
      useCases: ["coding"],
      keyFeatures: ["user management", "SSO", "data excluded from training", "policy controls", "audit logs"],
      sourceUrl: "https://github.com/features/copilot#pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "GitHub Copilot",
      planName: "Enterprise",
      pricePerSeat: 39,
      flatPrice: null,
      minSensibleSeats: 100,
      maxSensibleSeats: null,
      useCases: ["coding"],
      keyFeatures: ["everything in Business", "Copilot Chat in GitHub.com", "PR summaries", "fine-tuned models", "IP indemnity"],
      sourceUrl: "https://github.com/features/copilot#pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
   
    // GEMINI (Google)

    {
      toolName: "Gemini",
      planName: "Free",
      pricePerSeat: 0,
      flatPrice: null,
      minSensibleSeats: 1,
      maxSensibleSeats: 1,
      useCases: ["writing", "research", "mixed"],
      keyFeatures: ["Gemini 1.5 Flash", "basic chat", "limited usage"],
      sourceUrl: "https://one.google.com/about/plans",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "Gemini",
      planName: "Pro",
      pricePerSeat: 20,
      flatPrice: null,
      minSensibleSeats: 1,
      maxSensibleSeats: 1,
      useCases: ["writing", "research", "mixed", "data"],
      keyFeatures: ["Gemini 1.5 Pro", "1M context window", "Google Workspace integration", "image understanding"],
      sourceUrl: "https://one.google.com/about/plans",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "Gemini",
      planName: "Business",
      pricePerSeat: 24,
      flatPrice: null,
      minSensibleSeats: 2,
      maxSensibleSeats: null,
      useCases: ["writing", "research", "mixed", "data", "customer_support"],
      keyFeatures: ["Gemini in all Workspace apps", "admin controls", "data protection", "enterprise security"],
      sourceUrl: "https://workspace.google.com/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
   

    // OPENAI API (direct)
    {
      toolName: "OpenAI API",
      planName: "Pay-as-you-go",
      pricePerSeat: null,
      flatPrice: 0, 
      minSensibleSeats: 1,
      maxSensibleSeats: null,
      useCases: ["coding", "writing", "research", "customer_support", "data", "mixed"],
      keyFeatures: ["GPT-4o", "GPT-4o-mini", "o1", "embeddings", "fine-tuning", "pay per token"],
      sourceUrl: "https://openai.com/api/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
   

    // ANTHROPIC API (direct)

    {
      toolName: "Anthropic API",
      planName: "Pay-as-you-go",
      pricePerSeat: null,
      flatPrice: 0,
      minSensibleSeats: 1,
      maxSensibleSeats: null,
      useCases: ["coding", "writing", "research", "customer_support", "data", "mixed"],
      keyFeatures: ["Claude Haiku", "Claude Sonnet", "Claude Opus", "batch processing", "pay per token"],
      sourceUrl: "https://anthropic.com/api",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
   
    // WINDSURF
    {
      toolName: "Windsurf",
      planName: "Free",
      pricePerSeat: 0,
      flatPrice: null,
      minSensibleSeats: 1,
      maxSensibleSeats: 1,
      useCases: ["coding"],
      keyFeatures: ["unlimited autocomplete", "limited Cascade agent access", "evaluation tier"],
      sourceUrl: "https://windsurf.com/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "Windsurf",
      planName: "Pro",
      pricePerSeat: 15,
      flatPrice: null,
      minSensibleSeats: 1,
      maxSensibleSeats: 19,
      useCases: ["coding"],
      keyFeatures: ["unlimited autocomplete", "more Cascade agent flows", "all major models", "priority access"],
      sourceUrl: "https://windsurf.com/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
    {
      toolName: "Windsurf",
      planName: "Teams",
      pricePerSeat: 30,
      flatPrice: null,
      minSensibleSeats: 5,
      maxSensibleSeats: null,
      useCases: ["coding"],
      keyFeatures: ["centralised billing", "admin dashboard", "SSO", "shared team context"],
      sourceUrl: "https://windsurf.com/pricing",
      lastVerified: new Date("2025-05-01"),
      isActive: true,
    },
   
  ];
   
  module.exports = pricingData;